/*
 * CoA Universal Content Scaling
 * GeneratedContentCensus: Authoritative census of maps, instance profiles, and tiers.
 * Automatically generated by tools/content_census/generate_census.py
 */

#ifndef GENERATED_CONTENT_CENSUS_H
#define GENERATED_CONTENT_CENSUS_H

#include "ContentEra.h"
#include "ContentTier.h"
#include "Define.h"
#include <array>
#include <cstdint>

struct GeneratedInstanceProfile
{
    uint32 mapId;
    ContentEra era;
    ContentTier tier;
    uint32 intendedPlayers;
    bool isRaid;
    char const* name;
};

inline constexpr std::array<GeneratedInstanceProfile, 90> sGeneratedInstanceProfiles =
{{
    { 30, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Alterac Valley" },
    { 33, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Shadowfang Keep" },
    { 34, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Stormwind Stockade" },
    { 36, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Deadmines" },
    { 43, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Wailing Caverns" },
    { 44, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Monastery" },
    { 47, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Razorfen Kraul" },
    { 48, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Blackfathom Deeps" },
    { 70, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Uldaman" },
    { 90, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Gnomeregan" },
    { 109, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Sunken Temple" },
    { 129, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Razorfen Downs" },
    { 169, ContentEra::Custom, ContentTier::WORLD, 25, true, "Emerald Dream" },
    { 189, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Scarlet Monastery" },
    { 209, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Zul'Farrak" },
    { 229, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Blackrock Spire" },
    { 230, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Blackrock Depths" },
    { 249, ContentEra::WotLK, ContentTier::RAID_ENTRY, 10, true, "Onyxia's Lair" },
    { 269, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Opening of the Dark Portal" },
    { 289, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Scholomance" },
    { 309, ContentEra::Classic, ContentTier::RAID_ENTRY, 20, true, "Zul'Gurub" },
    { 329, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Stratholme" },
    { 349, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Maraudon" },
    { 389, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Ragefire Chasm" },
    { 409, ContentEra::Classic, ContentTier::RAID_MID, 40, true, "Molten Core" },
    { 429, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Dire Maul" },
    { 469, ContentEra::Classic, ContentTier::RAID_END, 40, true, "Blackwing Lair" },
    { 489, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Warsong Gulch" },
    { 509, ContentEra::Classic, ContentTier::RAID_ENTRY, 20, true, "Ruins of Ahn'Qiraj" },
    { 529, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Arathi Basin" },
    { 531, ContentEra::Classic, ContentTier::RAID_PINNACLE, 40, true, "Ahn'Qiraj Temple" },
    { 532, ContentEra::TBC, ContentTier::RAID_ENTRY, 10, true, "Karazhan" },
    { 533, ContentEra::WotLK, ContentTier::RAID_ENTRY, 10, true, "Naxxramas" },
    { 534, ContentEra::TBC, ContentTier::RAID_END, 25, true, "The Battle for Mount Hyjal" },
    { 540, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Hellfire Citadel: The Shattered Halls" },
    { 542, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Hellfire Citadel: The Blood Furnace" },
    { 543, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Hellfire Citadel: Ramparts" },
    { 544, ContentEra::TBC, ContentTier::RAID_ENTRY, 25, true, "Magtheridon's Lair" },
    { 545, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Coilfang: The Steamvault" },
    { 546, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Coilfang: The Underbog" },
    { 547, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Coilfang: The Slave Pens" },
    { 548, ContentEra::TBC, ContentTier::RAID_MID, 25, true, "Coilfang: Serpentshrine Cavern" },
    { 550, ContentEra::TBC, ContentTier::RAID_MID, 25, true, "Tempest Keep" },
    { 552, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Tempest Keep: The Arcatraz" },
    { 553, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Tempest Keep: The Botanica" },
    { 554, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Tempest Keep: The Mechanar" },
    { 555, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Auchindoun: Shadow Labyrinth" },
    { 556, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Auchindoun: Sethekk Halls" },
    { 557, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Auchindoun: Mana-Tombs" },
    { 558, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Auchindoun: Auchenai Crypts" },
    { 559, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Nagrand Arena" },
    { 560, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "The Escape From Durnholde" },
    { 562, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Blade's Edge Arena" },
    { 564, ContentEra::TBC, ContentTier::RAID_END, 25, true, "Black Temple" },
    { 565, ContentEra::TBC, ContentTier::RAID_ENTRY, 25, true, "Gruul's Lair" },
    { 566, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Eye of the Storm" },
    { 568, ContentEra::TBC, ContentTier::RAID_END, 10, true, "Zul'Aman" },
    { 572, ContentEra::Classic, ContentTier::DUNGEON_NORMAL, 5, false, "Ruins of Lordaeron" },
    { 574, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Utgarde Keep" },
    { 575, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Utgarde Pinnacle" },
    { 576, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "The Nexus" },
    { 578, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "The Oculus" },
    { 580, ContentEra::TBC, ContentTier::RAID_PINNACLE, 25, true, "The Sunwell" },
    { 585, ContentEra::TBC, ContentTier::DUNGEON_NORMAL, 5, false, "Magister's Terrace" },
    { 595, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "The Culling of Stratholme" },
    { 599, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Halls of Stone" },
    { 600, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Drak'Tharon Keep" },
    { 601, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Azjol-Nerub" },
    { 602, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Halls of Lightning" },
    { 603, ContentEra::WotLK, ContentTier::RAID_MID, 10, true, "Ulduar" },
    { 604, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Gundrak" },
    { 607, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Strand of the Ancients" },
    { 608, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Violet Hold" },
    { 615, ContentEra::WotLK, ContentTier::RAID_ENTRY, 10, true, "The Obsidian Sanctum" },
    { 616, ContentEra::WotLK, ContentTier::RAID_ENTRY, 10, true, "The Eye of Eternity" },
    { 619, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Ahn'kahet: The Old Kingdom" },
    { 624, ContentEra::WotLK, ContentTier::RAID_ENTRY, 10, true, "Vault of Archavon" },
    { 628, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Isle of Conquest" },
    { 631, ContentEra::WotLK, ContentTier::RAID_PINNACLE, 10, true, "Icecrown Citadel" },
    { 632, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "The Forge of Souls" },
    { 649, ContentEra::WotLK, ContentTier::RAID_END, 10, true, "Trial of the Crusader" },
    { 650, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Trial of the Champion" },
    { 658, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Pit of Saron" },
    { 668, ContentEra::WotLK, ContentTier::DUNGEON_NORMAL, 5, false, "Halls of Reflection" },
    { 724, ContentEra::WotLK, ContentTier::RAID_PINNACLE, 10, true, "The Ruby Sanctum" },
    { 880, ContentEra::Custom, ContentTier::WORLD, 25, true, "Setis (PvE)" },
    { 883, ContentEra::Custom, ContentTier::WORLD, 25, true, "Soggoth (PvE)" },
    { 889, ContentEra::Custom, ContentTier::WORLD, 25, true, "Snowgrave (PvE)" },
    { 890, ContentEra::Custom, ContentTier::WORLD, 25, true, "Atal'zull (PvE)" },
    { 936, ContentEra::Custom, ContentTier::DUNGEON_NORMAL, 5, false, "Vaults of the Inquisition" },
}};

inline GeneratedInstanceProfile const* FindGeneratedInstanceProfile(uint32 mapId)
{
    for (auto const& p : sGeneratedInstanceProfiles)
    {
        if (p.mapId == mapId)
            return &p;
    }
    return nullptr;
}

#endif // GENERATED_CONTENT_CENSUS_H
